### PR TITLE
Add frontend unit tests

### PR DESCRIPTION
**Pull request by bgonp**
Added frontend unit tests using jest and testing-library.

As part of the preparation work I split the single `App.jsx` file with all the components into separate files, so they can be tested separately. The diff is pretty large because of this, but actually, the components have been moved to other files without changes.

### CODE REVIEW

**Comment by rlamana** [comment]
@pchico83 is this repo being used for anything related to development? I mean, if the App component has changed maybe it affects the guides where we ask for changes in the code to fix it. But I think this particular repository was meant for the new getting started docs where no dev step is included (yet), right?

**Comment by pchico83** [comment]
> @pchico83 is this repo being used for anything related to development? I mean, if the App component has changed maybe it affects the guides where we ask for changes in the code to fix it. But I think this particular repository was meant for the new getting started docs where no dev step is included (yet), right?

@rlamana right, this repo is only used in the getting started guide

**Comment by bgonp** [comment]
@rlamana @pchico83 Soooo, is it okay to be merged? 😅

**Comment by rlamana** [comment]
Yes, you can merge! 🚀

**Pull request merged**
